modelName: "test_model"
modelId: "dummymodel"
modelType: "dummy"
modelInput: "floatvector"
modelOutput: "floatvector"
modelAccuracy: "1.0"
requestPath: "/v1/models/test_model:predict"
requestPort: "8500"
