[selector]
type = "round-robin"

[network]
redis = "dragonfly"
selector = "selector"
minio = "minio"
base = "mulambda.svc.cluster.local"

[companion]
[companion.model]
name = "test_model"
id = "dummymodel"
type = "dummy"
input = "floatvector"
output = "floatvector"
accuracy = 1.0
path = "/v1/models/test_model:predict"
port = 8500


[client]
id = "client"

[experiment]
name = "test"
author = "silv-io"
