[selector]
type = "round-robin"

[network]
redis = "dragonfly"
selector = "model-selector"
client = "client-service"
base = "mulambda.svc.cluster.local"

[companion]
[companion.model]
name = "test_model"
id = "dummymodel"
type = "dummy"
input = "floatvector"
output = "floatvector"
latency = 9999
accuracy = 1.0
path = "/v1/models/test_model:predict"
port = 8500


[client]
model_type = "dummy"
input_type = "floatvector"
output_type = "floatvector"
latency_weight = 0.5
accuracy_weight = 0.5
latency_range = [0, 1000]
