[selector]
type = "round-robin"
latency_buckets = [10, 30, 60, 90, 150, 240, 390, 630, 1020]

[network]
redis = "dragonfly"
selector = "selector"
minio = "minio"
base = "mulambda.svc.cluster.local"

[companion]
[companion.model]
name = "test_model"
id = "dummymodel"
type = "dummy"
input = "floatvector"
output = "floatvector"
accuracy = 1.0
path = "/v1/models/test_model:predict"
port = 8500

[dummy]
[dummy.delay]
base = 20
size_impact = 0.2
concurrency_impact = 0.5
max_jitter = 5
[dummy.features]
max_confidences = [0.9, 0.7, 0.5]
set_size_impact = 0.3


[client]
id = "client"

[experiment]
name = "test"
author = "silv-io"
target = "mulambda-client"
usecase = "scp"
concurrency = 4
amount = 100
size = 10
