[selector]
type = "round-robin"

[network]
redis = "dragonfly"
selector = "selector"
minio = "minio"
base = "mulambda.svc.cluster.local"

[companion]
[companion.model]
name = "test_model"
id = "dummymodel"
type = "dummy"
input = "floatvector"
output = "floatvector"
accuracy = 1.0
path = "/v1/models/test_model:predict"
port = 8500

[dummy]
[dummy.delay]
base = 1000
size_impact = 0.1
concurrency_impact = 0.1
max_jitter = 300
[dummy.confidence]
good = ["A"]
mid = ["B"]
bad = ["C"]
size_impact = 0.1


[client]
id = "client"

[experiment]
name = "test"
author = "silv-io"
