apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-backend
spec:
  selector:
    matchLabels:
      app: dummy-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-backend
    spec:
      containers:
        - name: dummy-backend
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-backend
spec:
  selector:
    app: dummy-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
