apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  selector:
    matchLabels:
      app: model
  replicas: 1
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: nginx
          ports:
            - containerPort: 80
        - name: companion
          image: agihi/mulambda-companion:latest
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
