apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: model-deployment-
  namespace: mulambda
spec:
  selector:
    matchLabels:
      app: model
  replicas: 1
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: nginx
          ports:
            - containerPort: 80
        - name: companion
          image: agihi/mulambda-companion
          env:
            - name: MULAMBDA_COMPANION_MODEL_ID
              value: {{ .Values.model.id }}
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: mulambda
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
