apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.modelId }}
  name: {{ .Values.modelId }}
  namespace: mulambda
spec:
  selector:
    matchLabels:
      app: {{ .Values.modelId }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.modelId }}
    spec:
      containers:
        - name: model
          image: tensorflow/serving:2.4.3
          imagePullPolicy: IfNotPresent
          args:
            - --port=9000
            - --rest_api_port=8500
            - --model_name={{ .Values.modelName }}
            - --model_base_path=s3://models/{{ .Values.modelName }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: 9000
          ports:
            - containerPort: 9000
            - containerPort: 8500
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: minio123
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: S3_ENDPOINT
              value: minio-service:9000
        - name: companion
          image: agihi/mulambda-companion
          env:
            - name: MULAMBDA_COMPANION__MODEL__ID
              value: {{ .Values.modelId | quote }}
            - name: MULAMBDA_COMPANION__MODEL__NAME
              value: {{ .Values.modelName | quote }}
            - name: MULAMBDA_COMPANION__MODEL__TYPE
              value: {{ .Values.modelType | quote }}
            - name: MULAMBDA_COMPANION__MODEL__INPUT
              value: {{ .Values.modelInput | quote }}
            - name: MULAMBDA_COMPANION__MODEL__OUTPUT
              value: {{ .Values.modelOutput | quote }}
            - name: MULAMBDA_COMPANION__MODEL__ACCURACY
              value: {{ .Values.modelAccuracy | quote }}
            - name: MULAMBDA_COMPANION__MODEL__PATH
              value: {{ .Values.requestPath | quote }}
            - name: MULAMBDA_COMPANION__MODEL__PORT
              value: {{ .Values.requestPort | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelId }}
  namespace: mulambda
spec:
  selector:
    app: {{ .Values.modelId }}
  ports:
    - name: grpc-tf-serving
      port: 9000
      targetPort: 9000
    - name: http-tf-serving
      port: 8500
      targetPort: 8500
  type: ClusterIP
