apiVersion: v1
kind: Namespace
metadata:
  name: mulambda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly-deployment
  namespace: mulambda
spec:
  selector:
    matchLabels:
      app: dragonfly
  replicas: 1
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      nodeSelector:
        ether.edgerun.io/zone: zone-c
        node-role.kubernetes.io/controller: "true"
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
  namespace: mulambda
spec:
  selector:
    app: dragonfly
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
