apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: mulambda
spec:
  selector:
    matchLabels:
      app: client-app
  replicas: 1
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: mulambda
        image: agihi/mulambda-client
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector:
        ether.edgerun.io/zone: zone-c
        node-role.kubernetes.io/worker: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: mulambda
spec:
  selector:
    app: client-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
